# Generated by Django 4.1.5 on 2024-11-26 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(blank=True, max_length=50, verbose_name='телеграм id')),
                ('tg_state', models.CharField(default='START', max_length=50, verbose_name='Состояние бота')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Компания')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('status', models.CharField(choices=[('PARTICIPANT', 'Участник'), ('SPEAKER', 'Спикер')], default='PARTICIPANT', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': ('Участник',),
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сумма')),
                ('donated_at', models.DateTimeField(default=datetime.datetime(2024, 11, 26, 7, 31, 16, 248990, tzinfo=datetime.timezone.utc), verbose_name='Время доната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donates', to='bot.user', verbose_name='Кто задонатил')),
            ],
            options={
                'verbose_name': ('Донат',),
                'verbose_name_plural': 'Донаты',
            },
        ),
    ]
