# Generated by Django 4.1.5 on 2024-11-26 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_active_alter_donate_donated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_nick',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ник в телеграм'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='donated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 13, 57, 2, 361617, tzinfo=datetime.timezone.utc), verbose_name='Время доната'),
        ),
    ]
