# Generated by Django 4.1.5 on 2024-11-27 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_user_tg_nick_alter_donate_donated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название лекции')),
                ('description', models.TextField(verbose_name='Описание лекции')),
                ('start_time', models.DateTimeField(verbose_name='Начало лекции')),
                ('end_time', models.DateTimeField(verbose_name='Конец лекции')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланирована'), ('ONGOING', 'Идёт'), ('COMPLETED', 'Завершена')], default='PLANNED', max_length=20, verbose_name='Статус лекции')),
            ],
            options={
                'verbose_name': 'Доклад',
                'verbose_name_plural': 'Доклады',
                'ordering': ['start_time'],
            },
        ),
        migrations.AlterField(
            model_name='donate',
            name='donated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 6, 12, 51, 871761, tzinfo=datetime.timezone.utc), verbose_name='Время доната'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PARTICIPANT', 'Участник'), ('SPEAKER', 'Спикер'), ('MANAGER', 'Менеджер')], default='PARTICIPANT', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='телеграм id'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата проведения программы')),
                ('lectures', models.ManyToManyField(related_name='programs', to='bot.lecture', verbose_name='Лекции')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lecture', to='bot.user', verbose_name='Докладчик'),
        ),
    ]
