# Generated by Django 4.1.5 on 2024-11-27 07:50

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_lecture_alter_donate_donated_at_alter_user_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donate",
            name="donated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 27, 7, 50, 7, 287475, tzinfo=datetime.timezone.utc),
                verbose_name="Время доната",
            ),
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Текст вопроса")),
                (
                    "asked_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 11, 27, 7, 50, 7, 288473, tzinfo=datetime.timezone.utc),
                        verbose_name="Время создания",
                    ),
                ),
                (
                    "answerer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions_to",
                        to="bot.user",
                        verbose_name="Кому",
                    ),
                ),
                (
                    "asker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions_from",
                        to="bot.user",
                        verbose_name="От кого",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
    ]
