# Generated by Django 4.1.5 on 2024-11-27 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_donate_donated_at_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ready_to_questions',
            field=models.BooleanField(default=False, verbose_name='Готов/не готов получать вопросы'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='donated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 7, 57, 2, 301443, tzinfo=datetime.timezone.utc), verbose_name='Время доната'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='asked_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 7, 57, 2, 301443, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
        ),
    ]
