# Generated by Django 4.1.5 on 2024-11-27 19:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0006_user_ready_to_questions_alter_donate_donated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Letters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": ("Рассылка",),
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="donate",
            name="donated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 27, 19, 57, 32, 126752, tzinfo=datetime.timezone.utc),
                verbose_name="Время доната",
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="asked_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 27, 19, 57, 32, 127752, tzinfo=datetime.timezone.utc),
                verbose_name="Время создания",
            ),
        ),
    ]
