# Generated by Django 4.1.5 on 2024-11-28 06:28

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0007_letters_alter_donate_donated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": ("Заявка",),
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.AlterField(
            model_name="donate",
            name="donated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 28, 6, 28, 7, 906054, tzinfo=datetime.timezone.utc),
                verbose_name="Время доната",
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="asked_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 28, 6, 28, 7, 907052, tzinfo=datetime.timezone.utc),
                verbose_name="Время создания",
            ),
        ),
    ]
