# Generated by Django 4.1.5 on 2024-11-28 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_application_alter_donate_donated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Принята/отклонена'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_from', to='bot.user', verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, verbose_name='Текст заявки'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='donated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 6, 43, 8, 756517, tzinfo=datetime.timezone.utc), verbose_name='Время доната'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='asked_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 6, 43, 8, 757519, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
        ),
    ]
